services:
  - type: web
    name: limitless-mcp
    env: node
    plan: free
    buildCommand: npm run sync-lifelogs && npm run build
    startCommand: node dist/server.js
    branch: main
    envVars:
      - key: LIMITLESS_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    disks:
      - name: data
        mountPath: /data
        sizeGB: 1
